spring.application.name=bykeeasy

# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false
spring.flyway.out-of-order=true
spring.flyway.locations=classpath:db/migration

# Server Configuration
server.port=8080
server.address=0.0.0.0

# Google Maps Configuration
google.maps.api.key=${GOOGLE_MAPS_API_KEY:AIzaSyBQmB8LBBHfWMlo7_jcFfwocBjfCZF76Lc

# SerpApi Configuration
serpapi.api.key=${SERPAPI_API_KEY:3ac9363c44bbf8eda6cb2031a3400e9dda585e28afd56124e46fd933027a11d0
